baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Static Website for A2"
theme = "nostyleplease"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  [params.theme_config]
    appearance        = "light"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true

